### ISSUE TITLE
目次の追加

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#12]
目次を追加します。

**Comment by hitenkoku** [comment]
目次の追加はReadmeの追加ということでしょうか？それであれば #11 で対処完了していますが……？

**Comment by YamatoSecurity** [comment]
あれ？
hayabusaのReadmeでは目次が追加されているけど、`https://github.com/Yamato-Security/hayabusa-rules`のReadmeに目次がないですよね？

**Comment by hitenkoku** [comment]
なるほど、TableOfContentsの意味だったんですね。了解しました。私の方で対応してみます。

**Comment by YamatoSecurity** [comment]
ありがとうございます！
あ、そうです。ToCを言いたかったです。すみません。

**Comment by hitenkoku** [comment]
#18 で作成対応しました。
Markdown All in Oneを利用しております。Visual Studio Codeで拡張機能として登録していたらREADMEでheadlineが変わったときに自動で変更が入るようになっています。
