### ISSUE TITLE
Converting rules with `convert.py` is a little slow. Optimize if possible.

### ISSUE THREAD

**Issue by hach1yon** [Yamato-Security/hayabusa-rules#129]
convert.pyによるルールの変換処理に時間がかかっている。原因はルールファイルを1ファイルずつ変換していること。まとめて変換すればOK。

**Comment by hitenkoku** [comment]
開発・検証のときに1回で30分ほどかかるので、検証とかのときに少しネック。
Github Actionでは頻度から考慮して問題なし
