### ISSUE TITLE
一部ルールで、null、'null'という値が入ってしまっている

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-rules#13]
## 発生しているバージョン

https://github.com/Yamato-Security/hayabusa-rules/commit/f8460b5f242f87ef8e34af0a0c26219df61e4577

## 発生している現象

以下のように(EMPTY)という値が入っているが、文字列の「(EMPTY)」として考えるべきなのか、
空の値「''」として考えるべきなのか不明な状態になっている。

https://github.com/Yamato-Security/hayabusa-rules/blob/f8460b5f242f87ef8e34af0a0c26219df61e4577/sigma/registry_event/win_registry_shell_open_keys_manipulation.yml#L13

調査をする必要があり、必要に応じて変換ツール、ルール側の更新が必要かもしれません。

**Comment by hitenkoku** [comment]
変換のもとになったSIGMAのrule (https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry_event/win_registry_shell_open_keys_manipulation.yml )を見ると 以下のように書いてある。このケースのイベントログを持ってこないと判断ができないためもう少し確認する。hayabusa-rules側というよりsigma側の変更が必要？

https://github.com/SigmaHQ/sigma/blob/5a48f68cc23508e25ba3f9b8686f7a9f33cdeed8/rules/windows/registry_event/win_registry_shell_open_keys_manipulation.yml#L34

**Comment by hitenkoku** [comment]
sigmaのルールで同様の利用がされているものがないかを確認したところ以下の5ルールでEMPTYを利用されている。

- rules/windows/registry_event/win_re_bypass_uac_using_delegateexecute.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_system_scripts.yml
- rules/windows/registry_event/win_registry_shell_open_keys_manipulation.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_session_manager.yml
- rules/windows/registry_event/sysmon_asep_reg_keys_modification_wow6432node_classes.yml

**Comment by YamatoSecurity** [comment]
<img width="398" alt="Screen Shot 2022-03-04 at 13 08 48" src="https://user-images.githubusercontent.com/71482215/156697734-c0aaedf4-0409-4681-8785-ece672d1d673.png">

上記のルールで確認しました。

EID 12,13,14のsysmon registryイベントはレジストリキーが無い場合は文字列の(Empty)になるので、今は正しいと思います。
<img width="1140" alt="Screen Shot 2022-03-04 at 13 08 37" src="https://user-images.githubusercontent.com/71482215/156697798-471694d8-3eb2-4465-8463-02d7350f69c9.png">

ただ、調べたら、`null`と`'null'`を使っているルールもあります。。

<img width="1240" alt="Screen Shot 2022-03-04 at 12 47 49" src="https://user-images.githubusercontent.com/71482215/156696034-9f115158-d4d4-413c-8411-9815789e9611.png">

null、'null'は恐らくフィールドが空の場合という意味になると思うので、変換時に `Field: '' `という風に変換する必要があるかも？

**Comment by hitenkoku** [comment]
nullとかの取り扱いも考えたほうが良さそうですね……hayabusa側でnullという文字列は特別扱いにはしていなかったはずなので、ルール変換側でnull(もしくは'null'も一緒？)を''にできるか、私の方でも確認してみますね

**Comment by hitenkoku** [comment]
(EMPTY)は問題なかったため、Imageタグのnullについて問題がないかを調査する

**Comment by YamatoSecurity** [comment]
Closed by https://github.com/Yamato-Security/hayabusa/pull/655
