### ISSUE TITLE
hayabusaレポジトリのtools/sigmaをhayabusa-rulesレポジトリに移動する

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-rules#15]
hayabusaレポジトリにあるtools/sigmaはツール変換のためのスクリプトであるため、hayabusaレポジトリではなくhayabusa-rulesレポジトリで管理をする。

**Comment by hitenkoku** [comment]
異動はさせましたが、hayabusaがsubmoduleとして指定しているrulesフォルダ内にtools/sigmacのテスト用yamlファイルが入ってしまっているため、サブモジュール側の紐付けを変更する必要がありそうです

**Comment by YamatoSecurity** [comment]
tools/simacにymlテストファイルがあったんですね。IDを全部「000000000-0000-0000-0000-000000000000」にして、exclude_rules.txtの設定で無視する方法は良いと思います！

**Comment by hitenkoku** [comment]
それではその形で対応をさせていただきますね。コメントありがとうございます。
