### ISSUE TITLE
convert.py can't convert big rules

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#150]
現在、76KBの`driver_load_vuln_drivers.yml`ルールの変換ができません。
コマンドラインから`./tools/sigmac -t hayabusa -c ./tools/config/generic/sysmon.yml -c ./tools/config/generic/windows-services.yml ./rules/windows/driver_load/driver_load_vuln_drivers.yml`を実行したら２秒で無事に変換されますが、このルールだけを`./rules/windows`に置いて、convert.pyで変換しようとしても、1時間待っても終わりませんでした。

**Comment by fukusuket** [comment]
The same issue was reproduced in my environment.

sigmac is currently executed with **[Popen.wait()](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.wait)** as follows.
https://github.com/Yamato-Security/hayabusa-rules/blob/v1.7.0/tools/sigmac/convert.py#L167-L170

According to the [Python official documentation](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.wait),
**Popen.wait() cause deadlock when child process generates enouch output...**

According to the above document, using **[Popen.communicate()](https://docs.python.org/3.10/library/subprocess.html#subprocess.Popen.communicate)** ended the conversion.
I'll test it some more and if it's okay, I'll create a PR.

Reference articles in Japanese:
https://qiita.com/HidKamiya/items/e192a55371a2961ca8a4#%E3%83%87%E3%83%83%E3%83%89%E3%83%AD%E3%83%83%E3%82%AF%E3%81%A8popencommunicate
