### ISSUE TITLE
Auto-merge is not working

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#166]
自動的にマージされる状態でauto-mergeを有効にしてみても、`Pull request is in clean status`というエラーで失敗します。
<img width="522" alt="Screen Shot 2022-10-15 at 7 35 44" src="https://user-images.githubusercontent.com/71482215/195987593-33b50716-76c8-45f5-96de-e0027258c5d4.png">

すぐマージされないようにPRのレビューなどの条件を付ける必要があるようです。
PRレビューが必要という条件をまた有効にしたけど、またapproveの問題が出てきました。
PATなどのアクセストークンを作って自動的にapproveするようにしてみます。

**Comment by hitenkoku** [comment]
もし想定している対応が難しかった場合は、pull-requestの作成を行うときに使っているgithub actionの作者が良さそうなものを使っているのでこちらで対応できないか検討してみるのはいかがでしょうか

https://github.com/peter-evans/enable-pull-request-automerge

**Comment by YamatoSecurity** [comment]
試行錯誤で色々苦戦しましたが、github-actionsからのPRをapproveするKodiak Botの導入で自動化できました。
Closed by https://github.com/Yamato-Security/hayabusa-rules/pull/180
