### ISSUE TITLE
変換される際にChannelが設定されないため、誤検知が出る

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#19]
ルールがSigmaからHayabusaに変換される際にChannelが設定されないため、誤検知が結構出ます。
serviceとcategoryフィールドを確認して、Channelを指定する必要があります。
categoryの場合はEventIDも指定する必要があります。

参考：
[logsource対応.pdf](https://github.com/Yamato-Security/hayabusa-rules/files/8191621/logsource.pdf)

このgenericな設定ファイルを使うと良さそう：https://github.com/SigmaHQ/sigma/blob/master/tools/config/generic/windows-services.yml

**Comment by hitenkoku** [comment]
一旦ルール関連なので担当をitibに変更しました
