### ISSUE TITLE
process_creationルールはSysmonのみ対応

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#20]
categoryがprocess_creationの場合はSysmon EID 1とSecurity  EID 4688の２種類を作る必要がありますが、現在はSysmonルールしか作成していないため、Security 4688のログを検知できません。

[logsource対応.pdf](https://github.com/Yamato-Security/hayabusa-rules/files/8191636/logsource.pdf)

注意点：
- 4688のフィールド名を書き換える必要がある。
    Image: hogehoge を NewProcessName: hogehogeに変換 
    ParentImage: hogehoge を ParentProcessName: hogehogeに変換 
- 4688にフィールドが無い場合も多いので、必要なフィールドがSysmonにしか無い場合は4688ルールを作らない。
   (例： ParentCommandLine, OriginalFileName, FileVersion等々がルールにある場合はSysmonルールだけ作る。PDFをご参考に。)

**Comment by hitenkoku** [comment]
fixed via #41
