### ISSUE TITLE
detectionキー配下で変換が誤ってしまっているルールの調査

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-rules#21]
refs #9  

detectionキー配下で変換が誤っていることにより正しく検知できないルールが無いかを調査するissue。

**Comment by hitenkoku** [comment]
571eee894bb3e224cb7f7c8af2e2fdce498f7bb7 で大幅に修正が入ったため、 571eee894bb3e224cb7f7c8af2e2fdce498f7bb7 に対して確認を行う

**Comment by hitenkoku** [comment]
確認完了しました。sigmaフォルダ配下のルールを調べて気になった点を列挙します。condtionに明らかに変換が誤っているような記載はありませんでした。

- 対応するキーがeventkey_alias.txtに存在しない(EventData直下にあれば自動で探査するため、eventkey_alias.txtに記載しなくても検知は可能)
  -  sigma\builtin\bits_client\win_bits_client_susp_local_file.yml : LocalName
  - sigma\builtin\bits_client\win_bits_client_susp_powershell_job.yml : processPath
  - sigma\builtin\bits_client\win_bits_client_susp_use_bitsadmin.yml : processPath
  - sigma\builtin\security\win_admin_share_access.yml : ShareUserName

  - condition文内に改行が入っており、改行後の最初の文字がパイプ文字となっており、yamlのsyntaxhighlightで見ると、その後ろに記載されているタグ(例えばtimeframe)がタグとして認識されていないように見えるためyamlとして条件を全て読めていない可能性がある？(hayabusa側ので改行処理の読み込みが適切になされているか確認が必要。現状yamlのパースエラーなどは出ていないため大丈夫とは思われる)
    - sigma\builtin\security\win_susp_failed_logons_explicit_credentials.yml
    - sigma\builtin\security\win_susp_failed_logons_single_process.yml
    - sigma\builtin\security\win_susp_failed_logons_single_source_kerberos.yml
    - sigma\builtin\security\win_susp_failed_logons_single_source_kerberos2.yml
    - sigma\builtin\security\win_susp_failed_logons_single_source_kerberos3.yml
    - sigma\builtin\security\win_susp_failed_logons_single_source_ntlm.yml
    - sigma\builtin\security\win_susp_failed_logons_single_source_ntlm2.yml
    - sigma\builtin\security\win_susp_failed_logons_single_source.yml
    - sigma\builtin\security\win_susp_failed_remote_logons_single_source.yml
    - sigma\builtin\security\win_susp_multiple_files_renamed_or_deleted.yml

**Comment by hitenkoku** [comment]
一部Channnelで変換ミスらしきものがあったため念のためissueを別に切っておきます

**Comment by hitenkoku** [comment]
@YamatoSecurity  一旦本チケットは問題なしということでcloseしても良いでしょうか？
それか、以下のルールのログについて対応するイベントログがないかどうかを確認して別途eventkey_alias.txtの修正を行うようにしておきましょうか？processPathについてはだいぶ怪しいので……

> 対応するキーがeventkey_alias.txtに存在しない(EventData直下にあれば自動で探査するため、eventkey_alias.txtに記載しなくても検知は可能)
> 
> sigma\builtin\bits_client\win_bits_client_susp_local_file.yml : LocalName
> sigma\builtin\bits_client\win_bits_client_susp_powershell_job.yml : processPath
> sigma\builtin\bits_client\win_bits_client_susp_use_bitsadmin.yml : processPath
> sigma\builtin\security\win_admin_share_access.yml : ShareUserName

**Comment by YamatoSecurity** [comment]
ちょっと調べてみます！

**Comment by YamatoSecurity** [comment]
countルールは１件以外は大丈夫そうですが、恐らくサンプルevtxが無いため、２件しかヒットしていません。
１件はそもそもルールが間違っていたので、ルールを直して今PRを出しています。
https://github.com/SigmaHQ/sigma/pull/3964
processPathとLocalNameはeventkey_alias.txtで定義されていないが、自動的にEventDataを探すようになったので、試したら、ルールが無事にヒットしました。
`ShareUserName`を使ってSigmaルールは今消えているので、削除か修正されたと思います。
@hitenkoku また不安なルールがあれば、教えてください！
ありがとうございました！
