### ISSUE TITLE
Bug: null keywords do not get converted properly

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#241]
When a rule has `null` in the fields, it should be converted as is (Ex: `null`) but instead it gets converted to `|re: ^$`

For example: `proc_creation_win_proc_wrong_parent.yml`

`python3 ./tools/sigmac -t hayabusa -c ./tools/config/generic/windows-audit.yml -c ./tools/config/generic/windows-services.yml rules/windows/process_creation/proc_creation_win_proc_wrong_parent.yml > test.yml`

In one of the fields, it should say `ParentImage: null` but instead it gets converted to `ParentImage|re: ^$`

**Comment by YamatoSecurity** [comment]
問題箇所が分かりました。
68〜70行目:
```
        elif value is None:
            # nullは正規表現で表す。これでいいのかちょっと不安
            return self.generateNode((transformed_fieldname+"|re", "^$"))
```

コメントアウトしたら、エラーが発生します。

`return self.generateNode((transformed_fieldname, "null"))`
にしてみたのですが、`Field: 'null'`に変換されて、シングルクォートに囲まれてしまうので、駄目です。

シングルクォートをどうやって無くすでしょう。。

**Comment by fukusuket** [comment]
問題箇所の共有ありがとうございます、助かります🙇 

PyYAMLでは、クォートなしの`null` と `None` がマッピングされるようで、
https://pyyaml.org/wiki/PyYAMLDocumentation#yaml-tags-and-python-types
YAML上でクォートなしの`null`を表現したいときは、Python上は`None`を渡すようです！

**Comment by YamatoSecurity** [comment]
なるほど〜
