### ISSUE TITLE
Event id 104 Log File Cleared

### ISSUE THREAD

**Issue by danhagg** [Yamato-Security/hayabusa-rules#310]
The Hayabusa detection for Event 104 "Log File Cleared"....  

Hayabusa also flags Event 104: "The Smartcard reader reported a class descriptor." from "WudfUsbccidDriver" as a Log File Cleared event.

**Comment by hitenkoku** [comment]
@danhagg  There are three rules with EventID of 104 as follows, do you know the file name of the rule you are detecting?

- https://github.com/Yamato-Security/hayabusa-rules/blob/0284ec9fe0cbc8b47fcadbe11de3236df324b13a/hayabusa/builtin/System/Sys_104_High_SysLogCleared.yml
- https://github.com/Yamato-Security/hayabusa-rules/blob/2f531a6b1437add41f092cd4c8f5947ce4924487/sigma/builtin/system/win_system_susp_eventlog_cleared.yml
- https://github.com/Yamato-Security/hayabusa-rules/blob/2f531a6b1437add41f092cd4c8f5947ce4924487/sigma/builtin/system/win_system_eventlog_cleared.yml

If you add `-p verbose` in hayabusa and run it, the filename of the RULE will be output. (It will be output in the RuleFile column)

**Comment by YamatoSecurity** [comment]
@danhagg Thank you for reporting this. Could you let us know the exact rule that is causing this (can be found out with the `-p verbose` output profile), as well as the `Channel` and `Provider` of the event?

**Comment by danhagg** [comment]
I will certainly run the query again tomorrow. We love using hayabusa and
want to help!

**Comment by YamatoSecurity** [comment]
@danhagg Great to hear! We are always very active trying to fine tune it so any feedback is always welcome.
