### ISSUE TITLE
test_files側のルールの記載がSIGMAになっているのでTestに変更する。

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-rules#32]
test_files側のルールの記載がSIGMAになっているのでTestに変更する。

テストルールがUpdated SIGMA rules count: 23の"SIGMA"ルールになっていますが「Test」に変えることはできますか？

_Originally posted by @YamatoSecurity in https://github.com/Yamato-Security/hayabusa/issues/452#issuecomment-1072816547_

**Comment by hitenkoku** [comment]
@YamatoSecurity 一応対象となっているファイルはtools/sigmacにおけるtest_rulesを変換した際の期待する変換を指しているのである意味ruletypeが「SIGMA」は正しいものになりますが、これを「TEST」にしてしまってよいのでしょうか？

**Comment by YamatoSecurity** [comment]
そうですね。元々Sigmaルールではありますが、ダウンロードする時に実際に使うSigmaルールと区別したいです。

**Comment by hitenkoku** [comment]
こちらは対応は完了していてdevelopブランチ側には入っていますが、まだmainブランチに入っていません

**Comment by YamatoSecurity** [comment]
Closed by https://github.com/Yamato-Security/hayabusa-rules/pull/33
