### ISSUE TITLE
Convert deprecated and unsupported rules

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#327]
Currently, deprecated windows rules in sigma are located in `sigma/rules-deprecated/windows` and unsupported rules are located in `sigma/rules-unsupported` (mixed with non-Windows rules as well). (Maybe one day they will be relocated to `sigma/rules-unsupported/windows`)
We would need to recursively search `sigma/rules-deprecated` and `sigma/rules-unsupported` and convert rules that have 
```
logsource: 
    product: windows
``` 
and ignore all other logsource products (non-Windows rules).

The deprecated rules should be converted and placed in:
`hayabusa-rules/sigma/deprecated/builtin` for non-sysmon rules and `hayabusa-rules/sigma/deprecated/sysmon` for sysmon rules.
The unsupported rules should be converted and placed in:
`hayabusa-rules/sigma/unsupported/builtin` for non-sysmon rules and `hayabusa-rules/sigma/unsupported/sysmon` for sysmon rules.

@fukusuket I am sorry to ask you too many things already.. There is no hurry, so whenever you are finished with the other issues could I ask you to look at this one as you are the most knowledgeable with the hayabusa converter?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Now that the performance guide is almost finished, I'd love to work on this issue!💪 Thank you :)

**Comment by YamatoSecurity** [comment]
Great, thanks so much!

**Comment by fukusuket** [comment]
@YamatoSecurity 
I have a question about spec! In my understanding, after implementation, I think that the converted yml file will be placed in the following folder hierarchy, is this correct?

current rules dir structure
```
rules/hayabusa/builtin
rules/hayabusa/sysmon
rules/sigma/builtin
rules/sigma/sysmon
```
+new spec dir structure(add deprecated and unsuppoerted folders)
```
rules/sigma/deprecated/builtin
rules/sigma/deprecated/sysmon
rules/sigma/unsupported/builtin
rules/sigma/unsupported/sysmon
```

**Comment by YamatoSecurity** [comment]
@fukusuket That is a good question. Since we are disabling deprecated and unsupported rules by default and can filter on status anyways, what do you think about keeping the simple 
```
rules/hayabusa/builtin
rules/hayabusa/sysmon
rules/sigma/builtin
rules/sigma/sysmon
```
structure and add the deprecated and unsupported rules inside the two sigma subdirectories?
(don't place them in a separate folder like the upstream sigma repository does)

**Comment by fukusuket** [comment]
@YamatoSecurity 
I agree with the above as it is simple and easy to understand :) I will try the implementation with this specification!
