### ISSUE TITLE
Keep `all of selection*` and `1 of selection*` as is

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#340]
@fukusuket Could I ask you to look into this when you have time?
I would like to keep all of the `all of selection*` and `1 of selection*` sections as they are originally to make rules easy to read.
So basically, the converter will just be used for the `logsource` adding the `Channel` and `EventID` (and sometimes `CommandLine`, etc... for process creation events.) but we won't need to do any complex and/or logic anymore now that hayabusa supports `all of selection*` and `1 of selection*`.

**Comment by fukusuket** [comment]
Thank you for your assignment:) I will try to implement it!💪
