### ISSUE TITLE
Add support Windows Defender detection result (EID:1116) on non-English OS

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa-rules#349]
There are currently 4 rules that output [WindowsDefender detection results(EID:1116)](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-microsoft-defender-antivirus?view=o365-worldwide). (separated by **SeverityName**)
- [Defender_1116_Crit_Alert.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/WindowsDefender/Defender_1116_Crit_Alert.yml)
- [Defender_1116_High_Alert.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/WindowsDefender/Defender_1116_High_Alert.yml)
- [Defender_1116_Low_Alert.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/WindowsDefender/Defender_1116_Low_Alert.yml)
- [Defender_1116_Med_Alert.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/WindowsDefender/Defender_1116_Med_Alert.yml)

detection block is as follows.
https://github.com/Yamato-Security/hayabusa-rules/blob/b7d47a2512f2dbd26940139156d497a2258a8491/hayabusa/builtin/WindowsDefender/Defender_1116_Crit_Alert.yml#L14-L18

However, the `SeverityName` field seems to be set to different values ​​depending on the OS language setting.
For example Japanese OS's `SeverityName` is `重大`(`Severe` when English OS). 
<img width="1432" alt="スクリーンショット 2023-03-26 23 50 29" src="https://user-images.githubusercontent.com/41001169/227786285-d3a07521-2fa8-44b0-97f2-ee182e05944c.png">
[Microsoft-Windows-Windows Defender%4Operational.zip](https://github.com/Yamato-Security/hayabusa-rules/files/11072094/Microsoft-Windows-Windows.Defender.4Operational.zip)

Therefore, non-English OS's WindowsDefender detection results are not output default Hayabusa rule setting([
The rule that detects EID 1116 is disabled by default](https://github.com/Yamato-Security/hayabusa-rules/blob/main/config/exclude_rules.txt#L7))

For the above reason, it seems better to use `Severity ID`, which is not affected by language settings. 
I couldn't find any official documentation about `Severity ID`, As far as I actually checked, it was the following mapping
- Severity Name: `Severe`(`重大`) -> Severity ID `5`
- Severity Name: `High`(`高`) -> Severity ID `4`

@YamatoSecurity  What do you think about it?

**Comment by YamatoSecurity** [comment]
@fukusuket That sounds better than the way I am doing it now. Indeed, let's change it to use the security ID instead.

**Comment by YamatoSecurity** [comment]
@fukusuket That sounds better than the way I am doing it now. Indeed, let's change it to use the security ID instead.

**Comment by fukusuket** [comment]
Thank you for your comment :) I'll make PR💪
