### ISSUE TITLE
Need update sigmac toolpath in GitHub Actions

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa-rules#357]
The `sigmac` have been removed from the Sigma repository due to the PR below :(
- https://github.com/SigmaHQ/sigma/pull/4157

It seems that the `sigmac` tool has been moved to the following repository instead.
- https://github.com/SigmaHQ/legacy-sigmatools

Due to the above change, it seems that GitHub Actions needs to be updated🤔

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much! I'll merge it and test it out.

**Comment by fukusuket** [comment]
Sorry, it's failing, I'll check!

**Comment by fukusuket** [comment]
@YamatoSecurity 
I fixed an error when `converter.py` executed. However, the Action is still failing, is the error below a problem? :(
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/4602311576/jobs/8131130418

**Comment by YamatoSecurity** [comment]
@fukusuket The conversion seems fine. The action fails because 357-update-githubactions is not a protected branch. The auto-merge will work when it is the main branch. Looks good so can you send a PR?
