### ISSUE TITLE
Comments are erased when converting rules

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#408]
@fukusuket 
Sorry I just noticed that comments get erased when converted. Is it possible to copy over the comments from the original sigma rules? This would be make reading and understanding the sigma rules a bit easier without having to look up the original rule.

**Comment by fukusuket** [comment]
I didn't realize the comment was gone... :(   Yes, I will check if it can be done!💪

**Comment by YamatoSecurity** [comment]
@fukusuket Any progress on this? Since these rules are being used in other projects it would be nice to keep the comments to help analysts when reviewing the rules.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Sorry, I didn't look into it...😅  so I'll look into it!!

**Comment by fukusuket** [comment]
memo:
https://github.com/pycontribs/ruyaml/issues/28
