### ISSUE TITLE
Error after updating rules in Hayabusa  - Is this a known issue?

### ISSUE THREAD

**Issue by remrem29** [Yamato-Security/hayabusa-rules#446]
After updating the rules in Hayabusa, then after running it against event logs it is starting to report that an error has occured and point to the logs

In the log file there are lots of entries like these

Errors were generated. Please check ./logs/errorlog-20230628_083322.log for details.
[WARN] Failed to parse rule file. (FilePath : /opt/hayabusa/rules/sigma/sysmon/threat-hunting/process_creation/proc_creation_win_powershell_abnormal_commandline_size.yml)
[WARN] A condition parse error has occured. An unusable character was found.
[WARN] Failed to parse rule file. (FilePath : /opt/hayabusa/rules/sigma/sysmon/threat-hunting/process_creation/proc_creation_win_powershell_import_module.yml)
[WARN] A condition parse error has occured. An unusable character was found.

Is there a reason and fix for this?

**Comment by YamatoSecurity** [comment]
@remrem29 which version of Hayabusa are you using?

**Comment by remrem29** [comment]
I'm on a Hayabusa 2.2.0-dev version running on linux

**Comment by YamatoSecurity** [comment]
@remrem29 That is most likely the problem. Please update to the latest version 2.6.0.
https://github.com/Yamato-Security/hayabusa/releases

**Comment by remrem29** [comment]
Check, will do - Is there an guide somewhere on how to upgrade an existing Hayabusa on linux? Do I need to recompile to get an new code or is there an easiere way to upgrade?

**Comment by YamatoSecurity** [comment]
This is also explained in the github readme. I will close this issue for now.
