### ISSUE TITLE
Add `sysmon` tag to sigma sysmon rules

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#453]
@fukusuket 
I noticed that we can speed up scans by quite a bit by reducing rules. There are many cases that sysmon is not installed so I want to add filtering to exclude sysmon rules by ignoring rules that have a tag of `sysmon`

`--exclude-tags` feature: https://github.com/Yamato-Security/hayabusa/issues/1118

Unfortunately there are no `sysmon` tags in sigma rules, so would it be possible to add a `sysmon` tag to any sysmon rule that does not have it already when doing conversion? (I think most Hayabusa sysmon rules have a `sysmon` tag already so we can just ignore when the tag is already present.)

**Comment by fukusuket** [comment]
@YamatoSecurity 
It would be nice to be able to filter by `sysmon` tag, I will implement it!💪
