### ISSUE TITLE
Sigma repository's `PowerShell Classic(Windows PowerShell.evtx)` rules are undetectable with `Hayabusa`

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa-rules#514]
**Describe the bug**
The `PowerShell Classic(Windows PowerShell.evtx)` related Sigma rule below cannot be detected because it checks the field under the **noname** `Data` field.

[/rules/windows/powershell/powershell_classic](https://github.com/SigmaHQ/sigma/tree/master/rules/windows/powershell/powershell_classic)

- [Nslookup PowerShell Download Cradle](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_abuse_nslookup_with_dns_records.yml)
- [Alternate PowerShell Hosts](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_alternate_powershell_hosts.yml)
- [Delete Volume Shadow Copies Via WMI With PowerShell](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_delete_volume_shadow_copies.yml)
- [PowerShell Downgrade Attack - PowerShell](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_downgrade_attack.yml)
- [PowerShell Called from an Executable Version Mismatch](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_exe_calling_ps.yml)
- [Netcat The Powershell Version](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_powercat.yml)
- [Remote PowerShell Session (PS Classic)](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_remote_powershell_session.yml)
- [Renamed Powershell Under Powershell Channel](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_renamed_powershell.yml)
- [Suspicious PowerShell Download](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_susp_download.yml)
- [Use Get-NetTCPConnection](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_susp_get_nettcpconnection.yml)
- [Zip A Folder With PowerShell For Staging In Temp - PowerShell](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_susp_zip_compress.yml)
- [Tamper Windows Defender - PSClassic](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_tamper_windows_defender_set_mp.yml)
- [Suspicious Non PowerShell WSMAN COM Provider](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_wsman_com_provider_no_powershell.yml)
- [Suspicious XOR Encoded PowerShell Command Line - PowerShell](https://github.com/SigmaHQ/sigma/blob/master/rules/windows/powershell/powershell_classic/posh_pc_xor_commandline.yml)

For example, following rule use `HostApplication` field, but this field is under `Data` field.
https://github.com/Yamato-Security/hayabusa-rules/blob/7692e0b34c5ac58e09c9d202ea4a9aa309c6a633/sigma/builtin/powershell/powershell_classic/posh_pc_abuse_nslookup_with_dns_records.yml#L26-L31

**Actual behavior**
These rules are not detectable.

**Expected behavior**
These rules are detectable.

**Additional context**
`Windows PowerShell.evtx` event data structure is as follows.
<img width="1440" alt="スクリーンショット 2023-10-25 21 31 41" src="https://github.com/Yamato-Security/hayabusa-rules/assets/41001169/bdbc7189-c485-4093-9bae-ef83f9d413dd">

**Comment by fukusuket** [comment]
At first I thought all I had to do was modify logsource_mapping.py, but after thinking about it more complex transformations were needed... ><

**Comment by fukusuket** [comment]
I will create a PR and ask the Sigma repository if it is possible to handle this with rules using `Data`.

**Comment by YamatoSecurity** [comment]
Thanks for creating this issue. Indeed, since the sigma rules cannot be used as is, it is probably better to fix them upstream in the sigma rules themselves. Might be possible to do with regex but would slow down performance. If the sigma rules search everything in the `Data` field then more chances for false positives...
Let's ask the sigma maintainers what they think.

What about treating the following aliases in Hayabusa specially and parse out the `HostApplication= `, etc... fields from the `Data` field:
```
ContextInfo
HostApplication
EngineVersion
HostName
```

Unfortunately `ContextInfo` needs to be used to map a different field for `ps_module` logs. The other fields do not seem to be used in other sigma rules but are defined in `eventkey_alias.txt` for some reason. (`EngineVersion,Event.EventData.EngineVersion`, etc...)
So if we implemented it in Hayabusa, we would have to first prioritize checking if `HostApplication= `, etc.. was in the `Data` field and if not, fall back to checking the alias defined in `eventkey_alias.txt`.

**Comment by fukusuket** [comment]
I see, it seems like using Data will increase FalsePositive... It might be a good idea to handle this on the Hayabusa side:)
I asked the Sigma project the following questions!
https://github.com/SigmaHQ/sigma/discussions/4510

**Comment by fukusuket** [comment]
The following PR has been changed to use `Data`, so close this issue.
https://github.com/SigmaHQ/sigma/pull/4519
