### ISSUE TITLE
Create new UUIDv4 IDs for new rules created

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#629]
@fukusuket I thought about this more and I think we should create new UUIDv4 IDs for the newly created rules. This is because IDs are meant to be unique and may be used for looking up the original rules. The only issue is that we should probably create the IDs in a determined way so that the new IDs do not change randomly. Since the UUIDv4 IDs should be very random to begin with, this could be as simple as just incrementing the last value by one. What do you think?

We might want to also add:
```
related:
    - id: 4976aa50-8f41-45c6-8b15-ab3fc10e79ed
      type: derived
```
where the `id` field is of the original rule.

This is not a high priority issue so can be done after BSides whenever you have time.

**Comment by fukusuket** [comment]
@YamatoSecurity 
>Since the UUIDv4 IDs should be very random to begin with, this could be as simple as just incrementing the last value by one. What do you think?

I have only one concern!🤔
I think that changing just one character at the end can cause people to misunderstand the same value when looking at it visually(Misunderstand that both have the same UUID)

As an alternative, For example, how about converting the original rule's UUID **hash value** into a UUID format?
(It will be a visually completely different UUID and It will be the same UUID every time unless the UUID of the original rule changes)

**Comment by YamatoSecurity** [comment]
@fukusuket That's a good point, the IDs will look to similar and cause confusion. Yes, if you can find a way to hash the values then that would be a better approach.

**Comment by fukusuket** [comment]
I'm going to look into the UUID specifications a little bit, but I think I can implement it using the following steps🤔
1. Original UUID (`4976aa50-8f41-45c6-8b15-ab3fc10e79ed`) ... `36`character
2. Get MD5Hash (`567b46f6f76f27469a0ac2dffa47524e`) ... `32`character
3. Convet MD5Hash into UUID format (`567b46f6-f76f2-7469-a0ac2-dffa47524e`) ... `36`character

I will try it!
