### ISSUE TITLE
Duplicate keys in alias definitions

### ISSUE THREAD

**Issue by matthieugras** [Yamato-Security/hayabusa-rules#649]
config/eventkey_alias.txt contains duplicates with different definitions, e.g:
![image](https://github.com/Yamato-Security/hayabusa-rules/assets/35115728/22073475-2499-4847-9071-4d56617c117c)

The file also contains duplicates with the same definition, e.g. param1 and param2.

**Comment by YamatoSecurity** [comment]
@matthieugras Thanks for notifying us. We fixed it so you can run `update-rules` to get the fixed rules and config.
