### ISSUE TITLE
Update actions to use the separate converter

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#673]
I would only like to host rules in this repository so I separated the converter tool to this separate repo: https://github.com/Yamato-Security/sigma-to-hayabusa-converter
@fukusuket Could you update the actions to download the tool from this repo so that we can delete the `tools` folder. I also renamed the tool to `sigma-to-hayabusa-converter.py` 

Please check this new repo to see if there is anything I forgot to update. (I updated the usage but did not check that it works)

**Comment by fukusuket** [comment]
Sounds good! I would love to implement it💪
