### ISSUE TITLE
Rule parse error(rules/windows/image_load/image_load_side_load_dbgmodel.yml)

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa-rules#682]
https://github.com/Yamato-Security/hayabusa-rules/actions/runs/9897802114/job/27343150866

I'll send a pull request to the Sigma repository because of the following rule.
https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_dbgmodel.yml

**Comment by fukusuket** [comment]
It seems to be already being addressed :) 
https://github.com/SigmaHQ/sigma/pull/4928

Once merged, it is expected to be corrected.

**Comment by nasbench** [comment]
Sigma PR merged. Sorry for the inconvenience.

**Comment by fukusuket** [comment]
@nasbench 
Thanks for letting me know and fixing it right away :)
