### ISSUE TITLE
Add correlation rules support tables to SupportedSigmaFieldModifiers.md

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#750]
@fukusuket 
Whenever you get some free time, could I ask you to add `Hayabusa supported correlation rules` and `Hayabusa un-supported correlations rules` tables  in https://github.com/Yamato-Security/hayabusa-rules/blob/main/doc/SupportedSigmaFieldModifiers.md as well? 

`Hayabusa supported correlation rules`:
| Correlation Rule            | Sigma Count | Hayabusa Count |
|-----------------------------|-------------|----------------|
| event_count                 | 0           | 0              |
| event_count (with group-by) | 0           | 1              |
| value_count                 | 0           | 0              |
| value_count (with group-by) | 0           |     1          |

`Hayabusa un-supported correlations rules` 
| Correlation Rule            | Sigma Count | Hayabusa Count |
|-----------------------------|-------------|----------------|
| temporal                 | 0           | 0              |
| temporal (with group-by) | 0           | 0              |
| value_count                 | 0           | 0              |
| value_count (with group-by) | 0           | 0              |

**Comment by fukusuket** [comment]
Yes, I would love to implement it!💪
