### ISSUE TITLE
 Feature/use windows services to convert rule #46

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/hayabusa-rules#91]
#46 の対応を一旦revertしたため、ルールのコンバートを管理するissueを一旦作成

**Comment by YamatoSecurity** [comment]
私が修正した後の`convert.py`で変換したら、全ルールで以下のエラーが出ます: 
```
[WARN] Failed to parse rule file. (FilePath : ../sigma/hayabusa_rules/builtin/win_susp_logon_newcredentials.yml)
[WARN] Detection node was not found.
[WARN] Failed to parse rule file. (FilePath : ../sigma/hayabusa_rules/builtin/win_alert_mimikatz_keywords.yml)
[WARN] Detection node was not found.
```
ルールの中身はこんな感じ:
<img width="1045" alt="Screen Shot 2022-08-18 at 21 36 12" src="https://user-images.githubusercontent.com/71482215/185396378-f1da24eb-01c2-443f-8864-3d0c69f32345.png">
`detection:`があるので、なぜ`Detection node was not found.`になっているのかわかりません。
@itiB 分かりますか？

**Comment by YamatoSecurity** [comment]
@itiB 確認できました。最後の`---`がパースエラーを起こしています。(私が修正した前のバージョンでもこうなっているので、私の修正は関係なさそうです→私が修正した後のバージョンをベースにしてください）
`yml_filename`、`yml_path`も不要なので、最後の３行を消せますか？

**Comment by itiB** [comment]
@YamatoSecurity 
Hayabusaルールにすでに変換されたファイルをもう一度Hayabusaルールに変更しようとして失敗しています。
convert.py のうらで動くSigmacにはhayabusaルールを食べさせられないのでエラーが出るのは仕方ないです...！

**Comment by itiB** [comment]
自分も実行しようとしたらエラーでること確認できました
```
❯ ./target/debug/hayabusa -f ~/Documents/Tools/BigEventLog.evtx -r hayabusa_rules
~~~~ たくさん空白が入る ~~~~

Excluded rules: 11
Noisy rules: 0
Rule parsing error rules: 2706

Deprecated rules: 0 (0.00%)
Experimental rules: 1835 (33.98%)
Stable rules: 100 (1.85%)
Test rules: 759 (14.05%)
Undefined rules: 2707 (50.12%)

Other rules: 2706
Sigma rules: 2695
Total enabled detection rules: 5401
```

**Comment by itiB** [comment]
`---` を消したらたしかにエラーが消えました。
yml の方式として `---` が入ることはたしかにありますがhayabusaルールには不要のはずなので convert.py 側で消します
